project:
  type: website
  output-dir: docs
  resources:
    - "usb/*"
    - "links/*"
    - "*.pdf"
    
  render:
    - "*.qmd"
    - "!slides/"

website:
  page-navigation: true

  # page-footer:
    # left: "`r sprintf('&copy; Copyright %s, Filippo Gambarota', format(Sys.Date(), '%Y'))`"
    # right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
      left:
        - href: index.qmd
          text: home
        - href: about.qmd
          text: about
        - href: https://filippogambarota.github.io/cv/
          target: _blank
          text: cv
        - href: teaching.qmd
          text: teaching
        - href: statnotes.qmd
          text: statistics notes
        - href: slides.qmd
          text: slides
        - href: coding.qmd
          text: coding

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
