---
engine: knitr
---

# Slides

This repository is a collections of my slides and talks.

## Methodological Slides

* Introduction to the Tidyverse - [Psicostat](https://psicostat.dpss.psy.unipd.it/index.html) 11/12/2020 - [PDF](slides/tidyverse_presentation/tidyverse_presentation.pdf)
* Creating an Academic Website with Hugo - [HTML](https://filippogambarota.github.io/hugo_tutorial/#1) - [Repository](https://github.com/filippogambarota/hugo_tutorial)
* How to conduct a bibliographic research (Italian) - [HTML](slides/bibresearch/bibresearch.html)

## Statistics

* Introduction to Meta-analysis - [PDF](slides/meta_analysis_presentation/meta_analysis_presentation.pdf)
* Tips on Power and Sensitivity analysis - [HTML](slides/socialneu_lab/lab_meeting_sensitivity/lab_meeting_sensitivity.html)
* Multivariate Meta-Analysis in the Multiverse - [Psicostat](https://psicostat.dpss.psy.unipd.it/index.html) 04/03/2022 - [HTML](slides/multivariate-meta_analysis/multivariate-multiverse.html) - [PDF](slides/multivariate-meta_analysis/multivariate-multiverse.pdf)
* Simulating meta-analysis - [Psicostat Workshops](https://psicostat.dpss.psy.unipd.it/index.html) 03/05/2023 - [HTML](slides/understanding-meta-simulations/slides/understanding-meta-simulations.html)
* Replicating or not? Statistical methods for replicability assessment - [Psicostat](https://psicostat.dpss.psy.unipd.it/index.html) 27/10/2023 - [HTML](slides/psicostat-replicability/psicostat-replicability.html)

## Consciousness

* Introduction to the Neural Correlate of Consciousness - [Mechanism of Consciousness and Error Monitoring Course - University of Padova] - [Slides](https://docs.google.com/presentation/d/1hRqtLqWsM4qi7SeMOmPYG1HsRrcnDrTzhluVk-neSB8/edit?usp=sharing)
* Introduction to the Scientific Study of Consciousness - [General Psychology Course - University of Padova] - [Slides](https://docs.google.com/presentation/d/1PdIhW8IfYUBBRST6MeLIUuLYAIC804Wt8sSdJKn2ZIg/edit?usp=sharing) [Italian]

## Working Memory

* Visual Working Memory and Face Processing - [Cognitive and Functional Bases of Intersubjectivity - University of Padova] - [Slides](https://docs.google.com/presentation/d/1qVY2WTcfNNQgXm92dcw1jd8wPkSU4N267HcSWYNEVB0/edit#slide=id.gc96481fd19_0_343)

# Talks

- [@AIP 2022](http://www.aipass.org/xxx-congresso-aip-plenario-padova-27-30-settembre-2022) - The relationship between Working Memory and Visual Consciousness - [Slides](https://docs.google.com/presentation/d/1tl_iAEJQrMEUTUJe8jWasOXmTtK8Jn70JOETVQIj6u0/edit#slide=id.g155cf4ac025_0_65) - [PDF](AIP-2022/AIP-2022.pdf)

## Unconscious Visual Working Memory: a critical review and Bayesian meta-analysis

- 3 minute talk - [Talk](https://youtu.be/saINoKK5XLY)

## Trackdown Package

* trackdown package - TASK4-2021 - [Slides](slides/trackdown/trackdown_task4/trackdown_task4.html)
* trackdown package - useR-2021 - [Slides](slides/trackdown/trackdown_useR/trackdown_user.html) - [Talk](trackdown/trackdown_useR/talk_user.mp4)
* trackdown package - SIPS-2021 - [Slides](slides/trackdown/trackdown_sips/trackdown_sips.html) - [Talk](slides/trackdown/trackdown_sips/talk_sips.mp4)
